### PR TITLE
allow advertising on linux

### PR DESCRIPTION
**Pull request by syoder**
Still a work in progress.

Here's how you'd use it:

On a linux box, you can do `rake compile` then `sudo bundle console` (for some reason using BlueZ requires sudo privileges).

Then, you can start an altbeacon advertisement with the following:
``` ruby
ScanBeacon::BlueZ.advertisement_bytes = "\xff\x18\x01\xbe\xac\xbe\xac\xbe\xac\x11\x11\x22\x22\x33\x33\x44\x44\x55\x55\x66\x66\x00\x09\x00\x08\xc5\x00"
ScanBeacon::BlueZ.start_advertising
```

To stop advertising:
``` ruby
ScanBeacon::BlueZ.stop_advertising
```

### CODE REVIEW

**Comment by csexton** [comment]
Is your user a member of the `dialout` group on linux? I believe that will give you access without having to run the scary `sudo`.

**Comment by syoder** [comment]
I am already a member of `dialout` - that works for usb devices that show up as modems, but doesn't seem to for Bluetooth dongles / BlueZ.

**Comment by davidgyoung** [comment]
For eddystone-eid we may not be able to run the whole Zarkorr process as root (because that would give full access to the keystore) so we may have to run a root process just to switch identifiers.

**Comment by csexton** [comment]
You would think the group for controlling who has access to the devices connected to your system would give you access to the devices connected to your system (>ლ)

I just did some quick looking around and it looks like BlueZ uses [libcap's capability](https://github.com/torvalds/linux/blob/master/include/linux/capability.h) for determining permissions. Looks like it here in [`hci_sock`](https://github.com/torvalds/linux/blob/master/net/bluetooth/hci_sock.c#L620-L664).

[This answer](http://unix.stackexchange.com/questions/96106/bluetooth-le-scan-as-non-root#answer-182559) on stack exchange says you can set that for an executable: 

```
sudo setcap 'cap_net_raw,cap_net_admin+eip' /path/to/bin
```

Seems more secure than `setuid`, but just as annoying to configure. But certainly safer than just running a privileged daemon. There may be a better approach.

**Pull request merged**
